// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAlbsvkFRUgrXUuOn-KZghQCyhACDqerk',
    appId: '1:634394183211:web:aedce521c9ab4a034b0c6e',
    messagingSenderId: '634394183211',
    projectId: 'shashwat-brew-project',
    authDomain: 'shashwat-brew-project.firebaseapp.com',
    storageBucket: 'shashwat-brew-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe-LBFS1D70_rmO0w0SqSbopvmCNIFZSo',
    appId: '1:634394183211:android:69b146cda9f6c4ed4b0c6e',
    messagingSenderId: '634394183211',
    projectId: 'shashwat-brew-project',
    storageBucket: 'shashwat-brew-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm78dvp8KYAHzm0KNLFXRudwq0iUugSz4',
    appId: '1:634394183211:ios:d7d79a4a1ffb30d64b0c6e',
    messagingSenderId: '634394183211',
    projectId: 'shashwat-brew-project',
    storageBucket: 'shashwat-brew-project.appspot.com',
    iosClientId: '634394183211-pavhphkrp779db053p2droeh8eiovt6q.apps.googleusercontent.com',
    iosBundleId: 'com.example.friendsNashta',
  );
}
